apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: revtec/blueimage:$BUILD_ID
          ports:
            - name: http-server
              containerPort: 80