apiVersion: v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  selector:
    app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: revtec/blueimage:$BUILD_ID
          ports:
            - containerPort: 80